# -*- coding: utf-8 -*-
"""2026-1802 - Calcul de Pf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nGa1Z2-xnIzZSjjdKrSAJzXqGRX_dLM
"""

import math
import numpy as np
import matplotlib.pyplot as plt

from autograd import grad
import autograd.numpy as anp
from scipy.stats import norm
from scipy.interpolate import interp1d
import sympy as sp
from scipy.integrate import nquad
from scipy.integrate import quad
import plotly.graph_objects as go

from scipy.optimize import minimize

import sys
sys.path.insert(0, r'C:\_workingDir\_SF\fiabilite')
from config.jcss_fc import loi_fc
from config.jcss_fy import loi_fy
import openturns as ot

"""[... docstring ...]"""


params_names = ['fc', 'fy']

class flexion_simple:
    def __init__(self, Med, As, b, h, d, Es, ecu, fc_params, fy_params, fc_otparams, fy_otparams, fac_c=1.1):
#Initialisation
        # Données fixes
        self.Med = Med
        self.As = As
        self.b = b
        self.h = h
        self.d = d
        self.Es = Es
        self.ecu = ecu

        # Données variables
        self.fc_mean, self.fc_std = fc_params
        self.fy_mean, self.fy_std = fy_params

        # Transformation isoprobabiliste (espace standard U → espace physique X)
        dist = []
        if 'fc' in params_names:
            dist.append(loi_fc(*fc_otparams))
        if 'fy' in params_names:
            dist.append(loi_fy(*fy_otparams))
        dist_X     = ot.JointDistribution(dist)
        self.T_inv = dist_X.getInverseIsoProbabilisticTransformation()

        # Constantes pour la fonction de performance
        self.A = As * d
        self.B = -0.5 * As**2 / b
        self.C = -Med
        self.Ap = 0.8 * b * d / (As * Es * ecu)
        self.Bp = 0.8 * b * d**2

#Définition de la fonction de performance et de ses dérivées
    #Cas aciers plastifiés
    def f_plast(self, u):
        x_point = self.T_inv(ot.Point(u))
        x1, x2  = x_point[0], x_point[1]
        return self.A * x2 + self.B * x2**2 / x1 + self.C

    def grad_f_plast(self, u):
        u_pt    = ot.Point(u)
        x_point = self.T_inv(u_pt)
        x1, x2  = x_point[0], x_point[1]
        J       = self.T_inv.gradient(u_pt)  # Jacobienne diagonale [2x2]
        dx1_du1 = J[0, 0]                    # ∂x1/∂u1 = sigma_ln*x1 (lognormale)
        dx2_du2 = J[1, 1]                    # ∂x2/∂u2 = sigma_fy   (normale)
        der_u1  = -(self.B * x2**2 / x1**2) * dx1_du1
        der_u2  = (self.A + 2 * self.B * x2 / x1) * dx2_du2
        return anp.array([der_u1, der_u2])

    def lap_f_plast(self, u):
        x_point = self.T_inv(ot.Point(u))
        x1, x2  = x_point[0], x_point[1]
        der_u1 = -(4*self.B**2*x2**4/x1**5) * self.fc_std
        der_u2 = (2*self.B/x1) * self.fy_std
        return anp.array([der_u1, der_u2])

    #Cas aciers non-plastifiés
    def f_nonplast(self, u):
        x1 = self.T_inv(ot.Point(u))[0]
        val = self.Bp * (-1 + (1 + 4 * self.Ap * x1)**0.5 - 0.1 * (-1 + (1 + 4 * self.Ap * x1)**0.5)**2 / (self.Ap**2 * x1)) + self.C
        return val

    def grad_f_nonplast(self, u):
        u_pt    = ot.Point(u)
        x1      = self.T_inv(u_pt)[0]
        dx1_du1 = self.T_inv.gradient(u_pt)[0, 0]  # ∂x1/∂u1
        der_u1  = self.Bp * (2 * self.Ap / (4 * self.Ap * x1 + 1)**0.5 - 0.1 * (4 * self.Ap * x1 - 2 * (4 * self.Ap * x1 + 1)**0.5 + 2) / (self.Ap**2 * x1**2 * (4 * self.Ap * x1 + 1)**0.5)) * dx1_du1
        return anp.array([der_u1, 0.0])

    def lap_f_nonplast(self, u):
        x1 = self.T_inv(ot.Point(u))[0]
        lap_u1 = -(self.Bp * (4 * self.Ap**4 * x1**3 + 0.4 * (-6 * self.Ap**2 * x1**2 + 4 * self.Ap * x1 * (4 * self.Ap * x1 + 1)**0.5 - 6 * self.Ap * x1 + (4 * self.Ap * x1 + 1)**0.5 - 1))) / (self.Ap**2 * x1**3 * (4 * self.Ap * x1 + 1)**1.5)
        return anp.array([lap_u1, 0.0])

    #Cas général
    def test_plast(self, u):
        x_point = self.T_inv(ot.Point(u))
        x1, x2  = x_point[0], x_point[1]
        alpha_init = (self.As * x2) / (0.8 * self.b * self.d * x1)
        est = (1 - alpha_init) / alpha_init * self.ecu
        return anp.where(est >= x2 / self.Es, 1.0, 0.0)

    def f(self, u):
        tp = self.test_plast(u)
        return tp * self.f_plast(u) + (1 - tp) * self.f_nonplast(u)

    def grad_f(self, u):
        tp = self.test_plast(u)
        return tp * self.grad_f_plast(u) + (1 - tp) * self.grad_f_nonplast(u)

    def lap_f(self, u):
        tp = self.test_plast(u)
        return tp * self.lap_f_plast(u) + (1 - tp) * self.lap_f_nonplast(u)


"""# Résultats"""

calc = flexion_simple(Med=0.40, As=11.3254e-4, b=0.5, h=0.8, d=0.72,
                    Es=200000, ecu=0.0035,
                    fc_params=(48, 4.8), fy_params=(550, 30),
                    fc_otparams=(40, 0.09), fy_otparams=(500,))

# --- Verification coherence ---
x0 = calc.T_inv(ot.Point([0.0, 0.0]))
print(f"T_inv([0,0]) : x_fc = {x0[0]:.4f} MPa  |  x_fy = {x0[1]:.4f} MPa")
print(f"  (mediane lognormale fc attendue ~ 47.8 MPa, mediane normale fy attendue ~ 549.4 MPa)")
print(f"f([0,0])     = {calc.f([0.0, 0.0]):.6f}  (> 0 = securite au point median)")
print(f"test_plast([0,0]) = {calc.test_plast([0.0, 0.0])}  (1.0 = aciers plastifies)")
x1_ref = calc.T_inv(ot.Point([1.0, 0.0]))
print(f"T_inv([1,0]) : x_fc = {x1_ref[0]:.4f} MPa  (doit etre > x_fc au point median)")
print()

borne = 6
val_u1 = np.linspace(-borne, borne, 400)
val_u2 = np.linspace(-borne, borne, 400)
U1, U2 = np.meshgrid(val_u1, val_u2)

f_vec = np.vectorize(lambda x, y: calc.f([x, y]))
F_val = f_vec(U1, U2)

plt.figure(figsize=(8, 8))
plt.contourf(U1, U2, F_val, levels=[-np.inf, 0, np.inf], colors=['#ffcccc', '#ccccff'])
plt.contour(U1, U2, F_val, levels=[0], colors='black', linewidths=2)
plt.axhline(0, color='black', lw=1, ls='--')
plt.axvline(0, color='black', lw=1, ls='--')
plt.xlabel('$u_1$ (fc)')
plt.ylabel('$u_2$ (fy)')
plt.title("Frontière d'état limite $f(u_1, u_2) = 0$")
plt.grid(True, linestyle=':', alpha=0.6)
plt.text(-4, -4, 'DÉFAILLANCE ($f < 0$)', color='red', fontweight='bold')
plt.text(1, 5, 'SÉCURITÉ ($f > 0$)', color='blue', fontweight='bold')
plt.show()
