# -*- coding: utf-8 -*-
"""2026-1802 - Calcul de Pf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nGa1Z2-xnIzZSjjdKrSAJzXqGRX_dLM
"""

import math
import re
import os
import numpy as np
import matplotlib.pyplot as plt

from autograd import grad
import autograd.numpy as anp
from scipy.stats import norm
from scipy.interpolate import interp1d
import sympy as sp
from scipy.integrate import nquad
from scipy.integrate import quad
import plotly.graph_objects as go

from scipy.optimize import minimize, brentq

import sys
sys.path.insert(0, r'C:\_workingDir\_SF\fiabilite')
from config.jcss_fc import loi_fc
from config.jcss_fy import loi_fy, SIGMA
import openturns as ot

"""[... docstring ...]"""


params_names = ['fc', 'fy']

class flexion_simple:
    def __init__(self, Med, As, b, h, d, Es, ecu, fc_otparams, fy_otparams, fac_c=1.1):
#Initialisation
        # Données fixes
        self.Med = Med
        self.As = As
        self.b = b
        self.h = h
        self.d = d
        self.Es = Es
        self.ecu = ecu

        # Transformation isoprobabiliste (espace standard U → espace physique X)
        dist = []
        if 'fc' in params_names:
            dist.append(loi_fc(*fc_otparams))
        if 'fy' in params_names:
            dist.append(loi_fy(*fy_otparams))
        dist_X     = ot.JointDistribution(dist)
        self.T_inv = dist_X.getInverseIsoProbabilisticTransformation()

        # Constantes pour la fonction de performance
        self.A = As * d
        self.B = -0.5 * As**2 / b
        self.C = -Med
        self.Ap = 0.8 * b * d / (As * Es * ecu)
        self.Bp = 0.8 * b * d**2

#Définition de la fonction de performance
    #Cas aciers plastifiés
    def g_ana_plast(self, u):
        x_point = self.T_inv(ot.Point(u))
        x1, x2  = x_point[0], x_point[1]
        return self.A * x2 + self.B * x2**2 / x1 + self.C

    #Cas aciers non-plastifiés
    def g_ana_nonplast(self, u):
        x1 = self.T_inv(ot.Point(u))[0]
        val = self.Bp * (-1 + (1 + 4 * self.Ap * x1)**0.5 - 0.1 * (-1 + (1 + 4 * self.Ap * x1)**0.5)**2 / (self.Ap**2 * x1)) + self.C
        return val

    #Cas général
    def test_plast(self, u):
        x_point = self.T_inv(ot.Point(u))
        x1, x2  = x_point[0], x_point[1]
        alpha_init = (self.As * x2) / (0.8 * self.b * self.d * x1)
        est = (1 - alpha_init) / alpha_init * self.ecu
        return anp.where(est >= x2 / self.Es, 1.0, 0.0)

    def g_ana(self, u):
        tp = self.test_plast(u)
        return tp * self.g_ana_plast(u) + (1 - tp) * self.g_ana_nonplast(u)


"""# Résultats"""

# --- Lecture des données du modèle DS ---
modelname = "test_pure_flexion"
path = os.path.join(r'C:\workspace\storage\admin\SF', modelname + '.ds')
with open(os.path.join(path, 'dsCad.txt'), 'r') as f:
    _cad = f.read()
with open(os.path.join(path, 'dsLoad.txt'), 'r') as f:
    _load = f.read()

def _parse(text, name):
    return float(re.search(rf'(?m)^\s*{re.escape(name)}\s*=\s*([\d.]+)', text).group(1))

b   = _parse(_cad, 'b')    # largeur section (m)
h   = _parse(_cad, 'h')    # hauteur section (m)
L   = _parse(_cad, 'L')    # longueur poutre (m)
phi = _parse(_cad, 'phi')  # diamètre armatures (mm)

n_bars = len(re.findall(r'REBAR\(', _cad))
As = n_bars * math.pi * (phi / 2e3) ** 2   # section totale acier (m²)

# Hauteur utile : centroïde des armatures (3e coordonnée des POINT dans les lits)
z_rebar = [float(v) for v in re.findall(
    r'pts\d+\.append\(POINT\([^,]+,\s*[^,]+,\s*([\d.]+)\)', _cad)]
d = h - sum(z_rebar) / len(z_rebar)        # distance fibre comprimée → centroïde aciers (m)

# Charge appliquée (valeur absolue, en MN)
F = abs(float(re.search(r"Z='(-?[\d.]+)'", _load).group(1)))   # MN

Med = F * L   # moment en console (MN·m)

Es  = 200000   # module Young acier (MPa)
ecu = 0.0035   # déformation ultime béton EC2

fck, fyk = 40, 500          # MPa
cov_fck, cov_fyk = None, None

calc = flexion_simple(Med=Med, As=As, b=b, h=h, d=d,
                    Es=Es, ecu=ecu,
                    fc_otparams=(fck, cov_fck), fy_otparams=(fyk, cov_fyk))

# --- Verification coherence ---
x0 = calc.T_inv(ot.Point([0.0, 0.0]))
print(f"T_inv([0,0]) : x_fc = {x0[0]:.4f} MPa  |  x_fy = {x0[1]:.4f} MPa")
print(f"  (mediane lognormale fc attendue ~ 47.8 MPa, mediane normale fy attendue ~ 549.4 MPa)")
print(f"g_ana([0,0]) = {calc.g_ana([0.0, 0.0]):.6f}  (> 0 = securite au point median)")
print(f"test_plast([0,0]) = {calc.test_plast([0.0, 0.0])}  (1.0 = aciers plastifies)")
x1_ref = calc.T_inv(ot.Point([1.0, 0.0]))
print(f"T_inv([1,0]) : x_fc = {x1_ref[0]:.4f} MPa  (doit etre > x_fc au point median)")
print()

size_visu = 32   # temporaire : grille etendue
n_visu    = 3    # nombre de valeurs u1 pour sample_frontier
val_u1 = np.linspace(-size_visu, size_visu, 50)
val_u2 = np.linspace(-size_visu, size_visu, 50)
U1, U2 = np.meshgrid(val_u1, val_u2)

f_vec = np.vectorize(lambda x, y: calc.g_ana([x, y]))
G_ana = f_vec(U1, U2)

# --- Échantillonnage de points sur la frontière g_ana = 0 (toutes les branches) ---
def sample_frontier(calc, n_scan=100):
    """
    Pour chaque u1, scanne u2 et trouve TOUS les zéros de g_ana = 0
    (détecte toutes les branches par changements de signe successifs).
    Utilise les globales : size_visu, fyk, cov_fyk, SIGMA.
    n_scan : résolution du scan u2 pour détecter les changements de signe.
    """
    if cov_fyk is None:
        u2_min = -(fyk / SIGMA + 1.645)
    else:
        u2_min = -1.0 / cov_fyk
    u2_low = max(-size_visu, u2_min)

    pts = []
    u2_scan = np.linspace(u2_low, size_visu, n_scan)
    for u1 in np.linspace(-size_visu, size_visu, 40):
        g_vals = [calc.g_ana([u1, u2]) for u2 in u2_scan]
        for i in range(len(u2_scan) - 1):
            if g_vals[i] * g_vals[i+1] < 0:
                u2_star = brentq(
                    lambda u2: calc.g_ana([u1, u2]), u2_scan[i], u2_scan[i+1])
                pts.append([u1, u2_star])
    return np.array(pts) if pts else np.zeros((0, 2))

frontier_pts = sample_frontier(calc)
print(f"Points sur la frontière : {len(frontier_pts)}")
if len(frontier_pts):
    print(f"  u1 : [{frontier_pts[:,0].min():.2f}, {frontier_pts[:,0].max():.2f}]")
    print(f"  u2 : [{frontier_pts[:,1].min():.2f}, {frontier_pts[:,1].max():.2f}]")

# --- Sélection des points HF : sous-échantillonnage uniforme ---
n_hf_target = 2 * n_visu
step = max(1, len(frontier_pts) // n_hf_target)
grid_hf = frontier_pts[::step]
print(f"grid_hf : {len(grid_hf)} points (1 sur {step})")

def _u2_low():
    if cov_fyk is None:
        return max(-size_visu, -(fyk / SIGMA + 1.645))
    return max(-size_visu, -1.0 / cov_fyk)

def _resample_arc(pts, n_out):
    diffs = np.diff(pts, axis=0)
    arc   = np.concatenate([[0], np.cumsum(np.sqrt((diffs**2).sum(axis=1)))])
    t     = np.linspace(0, arc[-1], n_out)
    return np.column_stack([np.interp(t, arc, pts[:, 0]),
                            np.interp(t, arc, pts[:, 1])])

def sample_frontier1(calc, n_out=10, n_u2=200, n_u1_scan=50, u1_tol=3.0):
    """
    Branche verticale : varie u2 décroissant, cherche u1 dans une fenêtre
    glissante autour du dernier point trouvé.
    Retourne n_out points équidistants par arc-length.
    """
    u2_lo   = _u2_low()
    pts     = []
    u1_prev = None
    for u2 in np.linspace(size_visu, u2_lo, n_u2):
        u1_scan = (np.linspace(-size_visu, size_visu, n_u1_scan) if u1_prev is None
                   else np.linspace(max(-size_visu, u1_prev - u1_tol),
                                    min( size_visu, u1_prev + u1_tol), n_u1_scan))
        g_vals = [calc.g_ana([u1, u2]) for u1 in u1_scan]
        found  = False
        for i in range(len(u1_scan) - 1):
            if g_vals[i] * g_vals[i+1] < 0:
                u1_star = brentq(lambda u1: calc.g_ana([u1, u2]),
                                 u1_scan[i], u1_scan[i+1])
                pts.append([u1_star, u2])
                u1_prev = u1_star
                found   = True
                break
        if not found and pts:
            break
    if len(pts) < 2:
        return np.zeros((0, 2))
    return _resample_arc(np.array(pts), n_out)

def sample_frontier2(calc, n_out=10, n_u1=200, n_u2_scan=50):
    """
    Branche horizontale : varie u1 décroissant (droite → gauche), cherche le
    premier croisement u2 (bas → haut = branche basse).
    Retourne n_out points équidistants par arc-length.
    """
    u2_lo   = _u2_low()
    u2_scan = np.linspace(u2_lo, size_visu, n_u2_scan)
    pts     = []
    for u1 in np.linspace(size_visu, -size_visu, n_u1):
        g_vals = [calc.g_ana([u1, u2]) for u2 in u2_scan]
        found  = False
        for i in range(len(u2_scan) - 1):
            if g_vals[i] * g_vals[i+1] < 0:
                u2_star = brentq(lambda u2: calc.g_ana([u1, u2]),
                                 u2_scan[i], u2_scan[i+1])
                pts.append([u1, u2_star])
                found = True
                break
        if not found and pts:
            break
    if len(pts) < 2:
        return np.zeros((0, 2))
    return _resample_arc(np.array(pts), n_out)

f1 = sample_frontier1(calc, n_out=10)
f2 = sample_frontier2(calc, n_out=10)
print(f"sample_frontier1 : {len(f1)} pts  u1=[{f1[:,0].min():.2f},{f1[:,0].max():.2f}]  u2=[{f1[:,1].min():.2f},{f1[:,1].max():.2f}]")
print(f"sample_frontier2 : {len(f2)} pts  u1=[{f2[:,0].min():.2f},{f2[:,0].max():.2f}]  u2=[{f2[:,1].min():.2f},{f2[:,1].max():.2f}]")

# --- Grille physique : fc ≥ 0 et fy ≥ 0 ---
def make_grid(fck, cov_fck, fyk, cov_fyk, size_visu, n):
    """
    Retourne n*n points (u1, u2) avec fc ≥ 0 et fy ≥ 0.
    - fc lognormale : toujours > 0, pas de contrainte sur u1
    - fy normale    : fy ≥ 0  →  u2 ≥ -mu_fy / sigma_fy
    """
    dist_fy  = loi_fy(fyk, cov_fyk)
    mu_fy    = dist_fy.getMean()[0]
    sigma_fy = dist_fy.getStandardDeviation()[0]
    u2_min   = max(-size_visu, -mu_fy / sigma_fy)   # seuil fy = 0

    u1_vals  = np.linspace(-size_visu, size_visu, n)
    u2_vals  = np.linspace(u2_min, size_visu, n)
    U1g, U2g = np.meshgrid(u1_vals, u2_vals)
    return np.column_stack([U1g.ravel(), U2g.ravel()])

grid_pts = make_grid(fck, cov_fck, fyk, cov_fyk, size_visu=size_visu, n=20)
print(f"Grille physique : {len(grid_pts)} points")
print(f"  u1 : [{grid_pts[:,0].min():.2f}, {grid_pts[:,0].max():.2f}]")
print(f"  u2 : [{grid_pts[:,1].min():.2f}, {grid_pts[:,1].max():.2f}]")

plt.figure(figsize=(8, 8))
plt.contourf(U1, U2, G_ana, levels=[-np.inf, 0, np.inf], colors=['#ffcccc', '#ccccff'])
plt.contour(U1, U2, G_ana, levels=[0], colors='black', linewidths=2)
plt.scatter(grid_pts[:, 0], grid_pts[:, 1],
            c='steelblue', s=8, zorder=4, alpha=0.6, label=f'grille physique ({len(grid_pts)} pts)')
if len(frontier_pts):
    plt.scatter(frontier_pts[:, 0], frontier_pts[:, 1],
                c='green', s=40, zorder=5, label='points frontière g=0')
plt.scatter(grid_hf[:, 0], grid_hf[:, 1],
            c='orange', s=100, zorder=6, marker='x', linewidths=2,
            label=f'grid_hf ({len(grid_hf)} pts autour coude)')
if len(f1):
    plt.scatter(f1[:, 0], f1[:, 1], c='red',    s=60, zorder=7, marker='^', label=f'frontier1 ({len(f1)} pts)')
if len(f2):
    plt.scatter(f2[:, 0], f2[:, 1], c='purple', s=60, zorder=7, marker='v', label=f'frontier2 ({len(f2)} pts)')
plt.axhline(0, color='black', lw=1, ls='--')
plt.axvline(0, color='black', lw=1, ls='--')
plt.xlabel('$u_1$ (fc)')
plt.ylabel('$u_2$ (fy)')
plt.title("Frontière d'état limite $g_{ana}(u_1, u_2) = 0$")
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend(loc='upper right')
outdir = os.path.dirname(os.path.abspath(__file__))
plt.savefig(os.path.join(outdir, 'check_g_ana.png'), dpi=100, bbox_inches='tight')
